<?php 
	require('inc/common.php');
	require('inc/home.php');
	require('inc/conocenos.php');
	require('inc/espacios.php');
	require('inc/eventos.php');
	require('inc/comunidad.php');
	require('inc/conocimiento.php');
	require('inc/membresias.php');
?>